source 'https://cdn.cocoapods.org'
source 'https://github.com/NielsenDigitalSDK/nielsenappsdk-ios-specs-dynamic.git'
use_frameworks!
platform :ios, '10.0'

target 'Segment-Nielsen-DCR_Example' do
  pod 'Segment-Nielsen-DCR', :path => '../'
  pod 'NielsenAppSDK', '~> 8.0'

  target 'Segment-Nielsen-DCR_Tests' do
    inherit! :search_paths

    pod 'OCMockito'
    pod 'Specta'
    pod 'Expecta'
  end
end
