use_frameworks!

target 'Segment-Nielsen-DCR_Example' do
  pod 'Segment-Nielsen-DCR', :path => '../'

  target 'Segment-Nielsen-DCR_Tests' do
    inherit! :search_paths

    pod 'OCMockito'
    pod 'Specta'
    pod 'Expecta'
  end
end
